[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fraction = "0.11.1"
rand = "0.8.5"
rocket = "0.4.11"
rocket_contrib = { version = "0.4.6", features = ["json"] }
